MIRICO_FIELD_MAPPINGS = {
    0: {"TagName": "timeStamp", "ValueType": "string"},
    1: {"TagName": "gasTypeId", "ValueType": "float"},
    2: {"TagName": "pathLengthMeters", "ValueType": "float"},
    3: {"TagName": "quality", "ValueType": "float"},
    4: {"TagName": "windBearingDegreesTo", "ValueType": "float"},
    5: {"TagName": "windSpeedMetersPerSecond", "ValueType": "float"},
    6: {"TagName": "pressureMillibar", "ValueType": "float"},
    7: {"TagName": "temperatureKelvin", "ValueType": "float"},
    8: {"TagName": "gasPpm", "ValueType": "float"},
    9: {"TagName": "gasType", "ValueType": "string"},
    10: {"TagName": "retroLongitude", "ValueType": "float"},
    11: {"TagName": "retroLatitude", "ValueType": "float"},
    12: {"TagName": "sensorAltitude", "ValueType": "float"},
    13: {"TagName": "sensorLongitude", "ValueType": "float"},
    14: {"TagName": "sensorLatitude", "ValueType": "float"},
    15: {"TagName": "retroName", "ValueType": "string"},
    16: {"TagName": "siteKey", "ValueType": "string"},
    17: {"TagName": "siteName", "ValueType": "string"},
    18: {"TagName": "retroAltitude", "ValueType": "float"},
}
